=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/MenuDataStoresSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="dataStoreType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="menuBar" >
					<xs:complexType>
						<xs:attribute name="id" use="required" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuBarItem" >
					<xs:complexType>
						<xs:attribute name="commandId" use="required" type="xs:string" />
						<xs:attribute name="parentMenuBarId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuItem" >
					<xs:complexType>
						<xs:attribute name="commandId" use="required" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuItemCollection" >
					<xs:complexType>
						<xs:attribute name="id" use="required" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="usesMenuSeparator" use="optional" type="xs:boolean" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>
				<xs:element name="copyMenuObject" >
					<xs:complexType>
						<xs:attribute name="referencedMenuDataStoreId" use="required" type="xs:string" />
						<xs:attribute name="referencedMenuObjectId" use="required" type="xs:string" />
						<xs:attribute name="id" use="optional" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>


	<xs:element name="menuDataStores">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="menuDataStore" type="dataStoreType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/CanCopyOnlyItemsInDataStore.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItemCollection id="RecentObjectsGroup"/>
		<menuItem commandId="RecentFiles" parentId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>
		<menuItem commandId="RecentlyChangedFiles" parentId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>
		<menuItem commandId="RecentLocations" parentId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>
		
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuItem commandId="ToolsSubmenuItem"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem"/>

		<!--We can add child RecentChanges to a child RecentFiles of of copied data store item RecentObjectsGroup,
		even though it is not explicitly defined in this data store (e.g., RecentFiles is not in data store SharedMenuObjects2).
		However, we cannot copy RecentFiles in this data store (SharedMenuObjects2), since it is not explicitly defined in this data store.
		Only items explicitly defined in data store can be copied within the same data store, or to a different data store.
		-->
		<menuItem commandId="RecentChanges" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"/>

		<!--copyMenuObject for RecentFiles is defined in SharedMenuObjects, so we can copy it in this or other data stores -->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"/>
		
		<menuItem commandId="RecentSubmissions" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentlyChangedFiles"/>

		<!--copyMenuObject RecentlyChangedFilesCopy below will result in error logged, since it references RecentlyChangedFiles in SharedMenuObjects2
		that is a child of RecentObjectsGroup that is copied to SharedMenuObjects2 from SharedMenuObjects, 
		however RecentlyChangedFiles is not defined in data store SharedMenuObjects2-->
		<copyMenuObject id="RecentlyChangedFilesCopy" 
		                referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentlyChangedFiles"/>
		
	</menuDataStore>
	<menuDataStore id="NoFileSelectedMenuObjects">
		<!--copyMenuObject below will result in error logged, since it references RecentLocations in SharedMenuObjects2
		that is a child of RecentObjectsGroup that is copied to SharedMenuObjects2 from SharedMenuObjects, 
		and RecentLocations is not defined in data store SharedMenuObjects2-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentLocations"/>

		<!--Example of copying copied RecentObjectsGroup from SharedMenuObjects2-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>
		
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/DuplicateDataStoreIds.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItem commandId="Errors"/>
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects">
		<menuItem commandId="EnterFullScreenMode"/>
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuItem commandId="Projects"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Errors"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/CustomErrors.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<!--Projects is determined as invalid by returning (null, loggedMessage) in ExtendibleTreeStructure.ConvertDataStoreItemWrapper()
			Therefore, this item and its children will be removed.-->
		<menuItem commandId="Projects"/>
		<menuItem commandId="RecentSubmissions" parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<!--RecentFiles is determined as invalid by returning (null, loggedMessage) in ExtendibleTreeStructure.ConvertDataStoreItemWrapper()
			Therefore, this item and its children will be removed.-->
		<menuItem commandId="RecentFiles"/>
		<menuItem commandId="RecentLocations" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"/>
		
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<!--Projects is determined as invalid by returning (null, loggedMessage) in ExtendibleTreeStructure.ConvertDataStoreItemWrapper()
			Therefore, this item will not be copied.-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<menuItem commandId="Errors"/>
		<!--RecentFiles is determined as invalid by returning (null, loggedMessage) in ExtendibleTreeStructure.ConvertDataStoreItemWrapper()
			Therefore, this item will not be copied under Errors.-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.Errors"/>
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/InvalidTopLevelDataStoreItems.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItem commandId="Projects"/>
		<menuItem commandId="Errors" parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<!--Git cannot be used as top level data store item (per override of DataStoresCache.IsValidTopLevelDataStoreItem(dataStoreItem))
			Therefore,  item will be removed.
		-->
		<menuItem commandId="Git"/>
		<menuItem commandId="RecentSubmissions" parentId="ExtendibleTreeStructure.Tests.CommandIds.Git"/>
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<!--Git cannot be used as top level data store item (per override of DataStoresCache.IsValidTopLevelDataStoreItem(dataStoreItem))
			Therefore, this item will be removed.
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Git"/>
	</menuDataStore>

	<menuDataStore id="NoFileSelectedMenuObjects">
		<menuBarItem commandId="FileMenuBarItem"/>

		<!--Git cannot be used as top level data store item (per override of DataStoresCache.IsValidTopLevelDataStoreItem(dataStoreItem))
			However, in this case, Git is top level ExtendibleTreeStructure.Tests.CommandIds.Git in SharedMenuObjects, however
			it is copied as child of FileMenuBarItem. Therefore, Git will not be removed in this data store.
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Git"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.FileMenuBarItem"/>
		
	</menuDataStore>
	
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/SuccessfulCacheBuildTests/TestFiles/IgnoreSomeDataStoreItems.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">

		<!--Projects is removed in SharedMenuObjects but not in SharedMenuObjects2
		based on convertDataStoreItemWrapper delegate parameter passed to DataStoresCache-->
		<menuBarItem commandId="Projects"/>
		<menuItem commandId="Git" parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>
		<menuItem commandId="EnterPresentationMode" parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<!--
		RecentlyChangedFiles and its children will be removed in SharedMenuObjects2 but not in SharedMenuObjects.
		-->
		<menuBarItem commandId="RecentlyChangedFiles"/>
		<menuItem commandId="RecentFiles" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentlyChangedFiles" />
		
		<menuItem commandId="RecentLocations" />

		<!--SaveToCloud will be removed in SharedMenuObjects-->
		<menuItem commandId="SaveToCloud" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentLocations" />
		<!--EncodingUtf8 will be removed in SharedMenuObjects2-->
		<menuItem commandId="EncodingUtf8" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentLocations" />
		<!--FindFile will be removed in both SharedMenuObjects and SharedMenuObjects2-->
		<menuItem commandId="FindFile" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentLocations" />
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentlyChangedFiles"/>

		<menuBarItem commandId="BuildMenuBarItem"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentLocations"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.BuildMenuBarItem"/>
	</menuDataStore>
	
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/SuccessfulCacheBuildTests/TestFiles/SortingDataStoreItems.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<!--Default value for priority is (int.MaxValue/2)-->
	<menuDataStore id="SharedMenuObjects">
		<!--This will be added as the last top level item in SharedMenuObjects.-->
		<menuItemCollection id="RecentObjectsCollection" usesMenuSeparator="true" />

		<menuItem commandId="RecentFiles" parentId="RecentObjectsCollection" />
		<menuItem commandId="RecentLocations" parentId="RecentObjectsCollection" priority="20" />
		<menuItem commandId="RecentlyChangedFiles" parentId="RecentObjectsCollection" priority="10" />

		<!--EncodingUtf8 will be copied under RecentObjectsCollection with priority set in SharedMenuObjects2-->
		<menuItem commandId="EncodingUtf8"/>
		<!--SaveFile will be copied under RecentObjectsCollection without changing the priority (which is null by default) in SharedMenuObjects2-->
		<menuItem commandId="SaveFile" />
		<!--SaveFileAs will be copied under RecentObjectsCollection with different priority in SharedMenuObjects2-->
		<menuItem commandId="SaveFileAs" priority="15"/>

		<!--Projects will have priority null, since the value is not explicitly set.
		Therefore, this item will appear after the items with set priorities.
		-->
		<menuItem commandId="Projects" />
		<!--This will be added as the first top level item in SharedMenuObjects.-->
		<menuItem commandId="Errors" priority="10"/>
		<menuItem commandId="BuildSolution" priority="20"/>

		
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuBarItem commandId="ViewMenuBarItem"/>

		<!--1. Copy RecentObjectsCollection item from SharedMenuObjects (along with its children) data store as a child 
		of ViewMenuBarItem in this store 
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="RecentObjectsCollection"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem" />

		<!--2. Add new children to copied RecentObjectsCollection-->
		<!--This will be added as the first child in copied RecentObjectsCollection-->
		<menuItem commandId="RecentChanges" parentId="RecentObjectsCollection" priority="3" />
		<!--This will be added as the last child in RecentObjectsCollection-->
		<menuItem commandId="RecentSubmissions" parentId="RecentObjectsCollection" />

		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.EncodingUtf8" 
		                parentId="RecentObjectsCollection" priority="12"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.SaveFile"
		                parentId="RecentObjectsCollection"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.SaveFileAs"
		                parentId="RecentObjectsCollection" priority="4"/>

		<!--if no value is specified for Priority, copied value will be used.-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Errors"
		                priority="30" />

		<!--The value of priority as copied from SharedMenuObjects is 20, however we change it to 5, therefore, this item
			will be the second top level item (the first will be FileMenuBarItem wit Priority=2)
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.BuildSolution"
		                priority="5"/>

		<!--This will be added as the first top level item.-->
		<menuBarItem commandId="FileMenuBarItem" priority="2"/>
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/SuccessfulCacheBuildTests/TestFiles/SuccessfulCacheBuildTests.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd"
	>
	<menuDataStore id="SharedMenuObjects">
		<menuItemCollection id="RecentObjectsGroup" usesMenuSeparator="true" />
		<menuItemCollection id="RecentObjectsCollection" parentId="RecentObjectsGroup"  />

		<menuItem commandId="RecentFiles" parentId="RecentObjectsCollection" priority="4"/>
		<menuItem commandId="RecentlyChangedFiles" parentId="RecentObjectsCollection" priority="3"/>
		<menuItem commandId="RecentLocations" parentId="RecentObjectsCollection" priority="2" />
		<menuItem commandId="RecentChanges" parentId="RecentObjectsCollection" priority="1"/>

		<menuItemCollection id="SharedToolsCollection"/>
		<menuItem commandId="Projects" parentId="SharedToolsCollection"/>
		<menuItem commandId="Errors" parentId="SharedToolsCollection"/>

		<menuItem commandId="SaveFile"/>

		<menuItemCollection id="CommonSearchMenuCollection" usesMenuSeparator="true" />
		<menuItem commandId="FindText" parentId="CommonSearchMenuCollection"/>
		<menuItem commandId="FindFile" parentId="CommonSearchMenuCollection"/>
	</menuDataStore>

	<menuDataStore id="NoFileSelectedMenuObjects">
		<menuBar id="NoFileSelectedDefaultMenuBar" />

		<menuBarItem commandId="ViewMenuBarItem" parentMenuBarId="NoFileSelectedDefaultMenuBar"/>
		
		<menuItem commandId="ToolsSubmenuItem" parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem"/>
		<menuItem commandId="Git" parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="SharedToolsCollection"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem"/>
		
		<menuItem commandId="AppearanceSubmenuItem" parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem" />

		<menuItemCollection id="PresentationMode" parentId="ExtendibleTreeStructure.Tests.CommandIds.AppearanceSubmenuItem" usesMenuSeparator="true"/>
		<menuItem commandId="EnterPresentationMode" parentId="PresentationMode" />
		<menuItem commandId="EnterFullScreenMode" parentId="PresentationMode" />

		<menuItemCollection id="VisibleCommandBars" parentId="ExtendibleTreeStructure.Tests.CommandIds.AppearanceSubmenuItem" usesMenuSeparator="true"/>

		<menuItem commandId="NavigationBars" parentId="VisibleCommandBar"/>
		<menuItem commandId="UserProfileCommands" parentId="VisibleCommandBars"/>
		
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="RecentObjectsGroup" 
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem"/>

		<menuBarItem commandId="FileMenuBarItem" parentMenuBarId="NoFileSelectedDefaultMenuBar"/>

		<menuItemCollection id="SaveFileCollection" parentId="ExtendibleTreeStructure.Tests.CommandIds.FileMenuBarItem" usesMenuSeparator="true"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.SaveFile" parentId="SaveFileCollection"/>
		<menuBarItem commandId="SaveFileAs" parentMenuBarId="SaveFileCollection"/>
	</menuDataStore>

	<menuDataStore id="TextFileMenuObjects">

		<copyMenuObject id="TextFileMenuObjectsMenuBar" referencedMenuDataStoreId="NoFileSelectedMenuObjects" 
		                referencedMenuObjectId="NoFileSelectedDefaultMenuBar"/>
		<menuBarItem commandId="EncodingMenuBarItem" parentMenuBarId="TextFileMenuObjectsMenuBar"/>
		<menuItem commandId="EncodingUtf8"/>

		<menuItemCollection id="TextFileSaveFileMenuItemsCollection" parentId="SaveFileCollection" usesMenuSeparator="false"/>
		<menuItem commandId="SaveToCloud" parentId="TextFileSaveFileMenuItemsCollection"/>

		<menuBarItem commandId="EditMenuBarItem" parentMenuBarId="TextFileMenuObjectsMenuBar"/>
	</menuDataStore>

	<menuDataStore id="CSharpFileMenuObjects">
		<copyMenuObject id="CSharpFileMenuObjectsMenuBar" referencedMenuDataStoreId="TextFileMenuObjects"
		                referencedMenuObjectId="TextFileMenuObjectsMenuBar"/>

		<menuBarItem commandId="BuildMenuBarItem" parentMenuBarId="CSharpFileMenuObjectsMenuBar"/>

		<menuItem commandId="BuildSolution" parentId="ExtendibleTreeStructure.Tests.CommandIds.BuildMenuBarItem"/>
		<menuItem commandId="BuildProject" parentId="ExtendibleTreeStructure.Tests.CommandIds.BuildMenuBarItem"/>

		<!--Copy menu objects in CommonSearchMenuCollection in data store SharedMenuObjects 
		into EditMenuBarItem that have been copied from menu store TextFileMenuObjects
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="CommonSearchMenuCollection" parentId="ExtendibleTreeStructure.Tests.CommandIds.EditMenuBarItem"/>

	</menuDataStore>

</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/CircularCopyItemReferences.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">

		<menuItem commandId="ToolsSubmenuItem" />

		<menuItem commandId="RecentFiles" parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem" />
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentlyChangedFiles"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem"/>
		<menuItem commandId="RecentSubmissions" parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem" />
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2" >

		<menuBarItem commandId="FileMenuBarItem"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentlyChangedFiles"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.FileMenuBarItem"/>

	</menuDataStore>
</menuDataStores>
