=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/MenuDataStoresSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="dataStoreType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="menuBar" >
					<xs:complexType>
						<xs:attribute name="id" use="required" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuBarItem" >
					<xs:complexType>
						<xs:attribute name="commandId" use="required" type="xs:string" />
						<xs:attribute name="parentMenuBarId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuItem" >
					<xs:complexType>
						<xs:attribute name="commandId" use="required" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuItemCollection" >
					<xs:complexType>
						<xs:attribute name="id" use="required" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="usesMenuSeparator" use="optional" type="xs:boolean" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>
				<xs:element name="copyMenuObject" >
					<xs:complexType>
						<xs:attribute name="referencedMenuDataStoreId" use="required" type="xs:string" />
						<xs:attribute name="referencedMenuObjectId" use="required" type="xs:string" />
						<xs:attribute name="id" use="optional" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>


	<xs:element name="menuDataStores">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="menuDataStore" type="dataStoreType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/SuccessfulCacheBuildTests/TestFiles/DataStoresReferencingEachOther.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItemCollection id="RecentObjectsCollection" usesMenuSeparator="true" />

		<menuItem commandId="RecentFiles" parentId="RecentObjectsCollection" />
		<menuItem commandId="RecentlyChangedFiles" parentId="RecentObjectsCollection" />
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.SaveToCloud"
						parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentlyChangedFiles" />

	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuBarItem commandId="ViewMenuBarItem"/>

		<!--1. Copy RecentObjectsCollection item from SharedMenuObjects (along with its children) data store as a child 
		of ViewMenuBarItem in this store 
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="RecentObjectsCollection"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem" />

		<!--2. Add new children to copied RecentObjectsCollection-->
		<menuItem commandId="RecentChanges" parentId="RecentObjectsCollection" />

		<menuItem commandId="SaveToCloud"/>
		<menuItem commandId="SaveFile" parentId="ExtendibleTreeStructure.Tests.CommandIds.SaveToCloud"/>
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/TransitiveChildAndCopyCircularReferences.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<!--ToolsSubmenuItem in SharedMenuObjects goes to child RecentFiles
	   RecentFiles goes to child Projects in SharedMenuObjects
	   Projects in SharedMenuObjects goes to copied menu object Projects in SharedMenuObjects2
	   Projects in SharedMenuObjects2 goes to child ToolsSubmenuItem in SharedMenuObjects2
	   ToolsSubmenuItem in SharedMenuObjects2 goes to copied menu object ToolsSubmenuItem in SharedMenuObjects
	   ToolsSubmenuItem in SharedMenuObjects goes to child RecentFiles, which is the menu object we started with
	   -->
	<menuDataStore id="SharedMenuObjects">

		<menuItem commandId="ToolsSubmenuItem" />

		<menuItem commandId="RecentSubmissions" parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem" />
		
		<menuItem commandId="RecentFiles" parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem" />

		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"/>
		
		<menuItem commandId="RecentChanges" parentId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem" />
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuItem commandId="Projects"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.ToolsSubmenuItem" 
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/InvalidChildDataStoreItems.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuBar id="CSharpFileMenuObjectsMenuBar"/>

		<!--Git menu item is invalid child for CSharpFileMenuObjectsMenuBar and will not be added to CSharpFileMenuObjectsMenuBar-->
		<menuItem commandId="Git" parentId="CSharpFileMenuObjectsMenuBar"/>
		<menuBarItem commandId="Projects" parentMenuBarId="CSharpFileMenuObjectsMenuBar"/>
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="CSharpFileMenuObjectsMenuBar"/>

		<!--EnterPresentationMode menu item is invalid child for CSharpFileMenuObjectsMenuBar and will not be added to CSharpFileMenuObjectsMenuBar-->
		<menuItem commandId="EnterPresentationMode" parentId="CSharpFileMenuObjectsMenuBar"/>
		<menuBarItem commandId="FileMenuBarItem" parentMenuBarId="CSharpFileMenuObjectsMenuBar"/>

	</menuDataStore>

	<menuDataStore id="NoFileSelectedMenuObjects">
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="CSharpFileMenuObjectsMenuBar"/>

		<!--SaveFile menu item is invalid child for CSharpFileMenuObjectsMenuBar and will not be added to CSharpFileMenuObjectsMenuBar-->
		<menuItem commandId="SaveFile" parentId="CSharpFileMenuObjectsMenuBar"/>
		<menuBarItem commandId="BuildSolution" parentMenuBarId="CSharpFileMenuObjectsMenuBar"/>
	</menuDataStore>
	
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/SuccessfulCacheBuildTests/TestFiles/CopyDataStoreItem.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItemCollection id="RecentObjectsCollection" usesMenuSeparator="true" />

		<menuItem commandId="RecentFiles" parentId="RecentObjectsCollection" />
		<menuItem commandId="RecentlyChangedFiles" parentId="RecentObjectsCollection" />
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuBarItem commandId="ViewMenuBarItem"/>

		<!--1. Copy RecentObjectsCollection item from SharedMenuObjects (along with its children) data store as a child 
		of ViewMenuBarItem in this store 
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="RecentObjectsCollection"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem" />

		<!--2. Add new children to copied RecentObjectsCollection-->
		<menuItem commandId="RecentChanges" parentId="RecentObjectsCollection" />
		<!--3. Add RecentSubmissions as a child to RecentFiles that is a child of copied RecentObjectsCollection-->
		<menuItem commandId="RecentSubmissions" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles" />
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/InvalidCopiedDataStoreItem.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItem commandId="Projects"/>
		<menuItem commandId="Errors" parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<menuItem commandId="SaveFile"/>
		<menuItem commandId="SaveFileAs" parentId="ExtendibleTreeStructure.Tests.CommandIds.SaveFile"/>
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<copyMenuObject referencedMenuDataStoreId="RecentObjectsGroup" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.EncodingUtf8"/>

		<menuBarItem commandId="BuildMenuBarItem"/>
		<copyMenuObject referencedMenuDataStoreId="RecentObjectsGroup" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.BuildProject" 
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.BuildMenuBarItem"/>
		
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.BuildSolution"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.BuildMenuBarItem" />
	</menuDataStore>

	<menuDataStore id="NoFileSelectedMenuObjects">
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2" 
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.EncodingUtf8"/>

		<menuBarItem commandId="BuildMenuBarItem"/>
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.BuildSolution"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.BuildMenuBarItem" />
		
	</menuDataStore>
	
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/SuccessfulCacheBuildTests/TestFiles/CopyDataStoreItemMultipleTimesInDataStore.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuBarItem commandId="ViewMenuBarItem"/>
		<menuItemCollection id="RecentObjectsGroup" parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem"/>
		<menuItem commandId="RecentlyChangedFiles" parentId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>
		<menuItem commandId="RecentLocations" parentId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">

		<!--Copy RecentObjectsGroup from SharedMenuObjects with the same id (Id value will be the same as the Id in copied 
		data store item in SharedMenuObjects, since we do not explicitly set the Id) in this data store as a top level data store 
		item (no parent Id specified).
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>

		<!--Add RecentFiles as a child to RecentObjectsGroup copied from SharedMenuObjects.
			Note, RecentFiles, along with its child Errors will appear under all copies of RecentObjectsGroup.
		-->
		<menuItem commandId="RecentFiles" parentId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"/>
		<menuItem commandId="Errors" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"/>

		<menuBarItem commandId="FileMenuBarItem"/>
		
		<!---Copy RecentObjectsGroup in SharedMenuObjects2 data store (which is a copy of RecentObjectsGroup in SharedMenuObjects2 with new child RecentFiles
		added in this data store) and add it as a child of FileMenuBarItem in this data store twice (once with new Id=RecentObjectsGroupCopy1,
		and another time with new Id=RecentObjectsGroupCopy2).
		Note, since the ids of data store items specified in data store should be unique, we need to change the id oc copied object
		if we copy the data store item more than once. However, we need to worry for Id being unique only for data store items specified in 
		copyMenuObject, and not of children of copied dat store items. For example RecentObjectsGroup has children with ids RecentlyChangedFiles
		and RecentLocations, which are copied multiple times.
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"
						id="RecentObjectsGroupCopy1"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.FileMenuBarItem"/>
		
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"
		                id="RecentObjectsGroupCopy2"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.FileMenuBarItem"/>

		<menuBarItem commandId="BuildMenuBarItem"/>

		<!---Make another copy of RecentObjectsGroup in SharedMenuObjects2 data store (which is a copy of RecentObjectsGroup in 
		SharedMenuObjects2 with new child RecentFiles
		added in this data store) and add it as a child of BuildMenuBarItem in this data store with new Id=RecentObjectsGroupCopy3.
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.MenuIds.RecentObjectsGroup"
		                id="RecentObjectsGroupCopy3"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.BuildMenuBarItem"/>

		<!--Add RecentSubmissions as a child of RecentLocations.
		Note, RecentLocations is not defined in this data store, but is a child of RecentObjectsGroup in SharedMenuObjects data store.
		Since RecentObjectsGroup is copied to this data store multiple times (as top level data store item, a well as a child of  
		FileMenuBarItem and BuildMenuBarItem), the children (including RecentSubmissions) is copied multiple times too.
		As a result, RecentSubmissions will be added as a child under all copies of RecentLocations in this data store).		
		-->
		<menuItem commandId="RecentSubmissions" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentLocations"/>
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/SuccessfulCacheBuildTests/TestFiles/CopyingCopyOfDataStoreItem.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItemCollection id="RecentObjectsCollection" usesMenuSeparator="true" />

		<menuItem commandId="RecentFiles" parentId="RecentObjectsCollection" />
		<menuItem commandId="RecentlyChangedFiles" parentId="RecentObjectsCollection" />
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuBarItem commandId="ViewMenuBarItem"/>

		<!--1. Copy RecentObjectsCollection item from SharedMenuObjects (along with its children) data store as a child 
		of ViewMenuBarItem in this store 
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects" referencedMenuObjectId="RecentObjectsCollection"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.ViewMenuBarItem" />

		<!--2. Add new children to copied RecentObjectsCollection-->
		<menuItem commandId="RecentChanges" parentId="RecentObjectsCollection" />
	</menuDataStore>

	<menuDataStore id="NoFileSelectedMenuObjects">
		<menuBar id="NoFileSelectedDefaultMenuBar" />
		<menuBarItem commandId="FileMenuBarItem" parentMenuBarId="NoFileSelectedDefaultMenuBar"/>

		<!--Copy RecentObjectsCollection from SharedMenuObjects2 data store (which in turn was copied from SharedMenuObjects2 into SharedMenuObjects2)
		as a child of FileMenuBarItem-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects2" referencedMenuObjectId="RecentObjectsCollection"
		                parentId="ExtendibleTreeStructure.Tests.CommandIds.FileMenuBarItem" />

		<!--2. Add new children to copied RecentObjectsCollection-->
		<menuItem commandId="RecentLocations" parentId="RecentObjectsCollection" />
		<menuItem commandId="RecentSubmissions" parentId="RecentObjectsCollection" />

		<!--3. 'Errors' menu item will be added as a child to RecentChanges that is a child of 
			RecentObjectsCollection in SharedMenuObjects2. Since RecentObjectsCollection and its children are copied from SharedMenuObjects2
			we can add new children to RecentObjectsCollection as well as any of its children (or children of children, etc).
		-->
		<menuItem commandId="Errors" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentChanges" />
	</menuDataStore>
</menuDataStores>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/InvalidParentIds.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<menuItem commandId="RecentFiles"/>
		<menuItem commandId="RecentLocations" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"/>
	</menuDataStore>

	<menuDataStore id="SharedMenuObjects2">
		<menuBar id="VisibleCommandBars"/>
		<!--RecentFiles is copied from SharedMenuObjects, however it will not be added as a child to VisibleCommandBars, 
		since it cannot be child of menu bar VisibleCommandBars
		-->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.RecentFiles"
		                parentId="VisibleCommandBars"/>

		<!--EnterPresentationMode does not exist in this data store and is not copied over from other data stores,
			therefore an error will be logged for data tore item with commandId=Errors. It still will be in cache (without parent data) 
		-->
		<menuItem commandId="Errors" parentId="ExtendibleTreeStructure.Tests.CommandIds.EnterPresentationMode"/>

		<!--RecentLocations is copied from SharedMenuObjects. However, since RecentFiles is not added as a child to
		VisibleCommandBars, Projects will not be under VisibleCommandBars.
		Therefore an error will be logged for data tore item with commandId=Projects. Projects will still be in cache (without parent data)	
		-->
		<menuItem commandId="Projects" parentId="ExtendibleTreeStructure.Tests.CommandIds.RecentLocations"/>
	</menuDataStore>

</menuDataStores>
