=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/MenuDataStoresSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="dataStoreType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="menuBar" >
					<xs:complexType>
						<xs:attribute name="id" use="required" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuBarItem" >
					<xs:complexType>
						<xs:attribute name="commandId" use="required" type="xs:string" />
						<xs:attribute name="parentMenuBarId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuItem" >
					<xs:complexType>
						<xs:attribute name="commandId" use="required" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>

				<xs:element name="menuItemCollection" >
					<xs:complexType>
						<xs:attribute name="id" use="required" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="usesMenuSeparator" use="optional" type="xs:boolean" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>
				<xs:element name="copyMenuObject" >
					<xs:complexType>
						<xs:attribute name="referencedMenuDataStoreId" use="required" type="xs:string" />
						<xs:attribute name="referencedMenuObjectId" use="required" type="xs:string" />
						<xs:attribute name="id" use="optional" type="xs:string" />
						<xs:attribute name="parentId" use="optional" type="xs:string" />
						<xs:attribute name="priority" use="optional" type="xs:int" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>


	<xs:element name="menuDataStores">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="menuDataStore" type="dataStoreType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== artakhak/ExtendibleTreeStructure/ExtendibleTreeStructure.Tests/ErrorTests/TestFiles/CopyDataStoreItemReferencesItself.xml
<?xml version="1.0" encoding="utf-8" ?>
<menuDataStores
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="http://oroptimizer.com/ExtendibleTreeStructure/TestsXmlSchemas/MenuDataStoresSchema.xsd">
	<menuDataStore id="SharedMenuObjects">
		<!--Projects references itself and will be removed. -->
		<copyMenuObject id="Projects" referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>
		
		<menuItem commandId="BuildSolution" parentId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>

		<menuItem commandId="Errors"/>
		<copyMenuObject id="ErrorsCopy" referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Errors"/>
	</menuDataStore>
	<menuDataStore id="SharedMenuObjects2">
		<!--Projects in SharedMenuObjects references itself and will be removed. -->
		<copyMenuObject referencedMenuDataStoreId="SharedMenuObjects"
		                referencedMenuObjectId="ExtendibleTreeStructure.Tests.CommandIds.Projects"/>
	</menuDataStore>
	
</menuDataStores>
